{
 "title": "Luna2000",
 "tags": [ "Huawei" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Batterij status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "luna2000_running_status",
     "legendFormat": "{{inverter}} Batterij #{{battery}}"
    }
   ]
  },
  {
   "title": "Batterij Capiciteit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "luna2000_battery_capacity",
     "legendFormat": "{{inverter}} Batterij #{{battery}}"
    }
   ]
  },
  {
   "title": "Luna totals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "luna2000_battery_capacity",
     "legendFormat": "{{inverter}} battery #{{battery}}"
    }
   ]
  },
  {
   "title": "Batterij bus voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "luna2000_bus_voltage",
     "legendFormat": "{{inverter}} Batterij #{{battery}}"
    }
   ]
  },
  {
   "title": "Total opgeladen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "increase(luna2000_total_charge[5m])",
     "legendFormat": "{{inverter}} Batterij #{{battery}}"
    }
   ]
  },
  {
   "title": "Total ontladen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "increase(luna2000_total_discharge[5m])",
     "legendFormat": "{{inverter}} Batterij #{{battery}}"
    }
   ]
  }
 ]
}