{
 "title": "Power meter",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "power_meter_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Terug leveren aan het net",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "type": "threshold"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "power_meter_phase_voltage", "legendFormat": "Fase {{phase}}" }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "power_meter_phase_current", "legendFormat": "Fase {{phase}}" }
   ]
  },
  {
   "title": "Net voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "power_meter_phase_voltage", "legendFormat": "Fase {{phase}}" }
   ]
  },
  {
   "title": "Net kWh van en naar",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "increase(power_meter_positive_active_electricity{})",
     "legendFormat": "kWh naar het net"
    },
    {
     "expr": "increase(power_meter_reverse_active_power{})",
     "legendFormat": "kWh van het net"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    { "expr": "power_meter_frequency", "legendFormat": "Frequency" }
   ]
  },
  {
   "title": "Net ampere",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "power_meter_phase_current", "legendFormat": "Fase {{phase}}" }
   ]
  },
  {
   "title": "Net watt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "power_meter_phase_active_power", "legendFormat": "Fase {{phase}}" }
   ]
  }
 ]
}