{
 "title": "Sun2000",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Net fase voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "sun2000_phase_voltage", "legendFormat": "{{inverter}} Fase {{phase}}" }
   ]
  },
  {
   "title": "Net fase ampere",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "sun2000_phase_current", "legendFormat": "{{inverter}} Fase {{phase}}" }
   ]
  },
  {
   "title": "Zonnepanelen strings voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "sun2000_pv_voltage", "legendFormat": "{{inverter}} String {{string}}" }
   ]
  },
  {
   "title": "Zonnepanelen strings voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "((sum(sum by (string) (sun2000_pv_voltage)) / 2) * (sum(sum by (string) (sun2000_pv_current)) / 2)) / 1000",
     "legendFormat": "{{inverter}} String {{string}}"
    }
   ]
  },
  {
   "title": "Active power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    { "expr": "sun2000_active_power", "legendFormat": "{{inverter}} Active power" },
    { "expr": "sun2000_reactive_power", "legendFormat": "{{inverter}} Reactive power" }
   ]
  },
  {
   "title": "Zonnepanelen strings ampere",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "sun2000_pv_current", "legendFormat": "{{inverter}} String {{string}}" }
   ]
  },
  {
   "title": "Omvormer efficiency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "sun2000_inverter_efficiency", "legendFormat": "{{inverter}} Efficiency" }
   ]
  },
  {
   "title": "Net frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    { "expr": "sun2000_grid_frequency", "legendFormat": "{{inverter}} Frequency" }
   ]
  }
 ]
}